common:
  execute: true
  group_name: ur_manipulator
  ik_link: tool0
  max_velocity: 0.3
  max_acceleration: 0.3
  print_joints: true   # activa logs

steps:
  - name: home
    target_xyz: [0.40, 0.00, 0.55]
    target_rpy: [3.14, 0.0, -1.57]
    seed_from_joint_states: false
    seed_joints: [0.00, -1.80, 1.80, 3.0, -1.57, 0.00]
    sleep_after: 1.0

  - name: pick
    target_xyz: [0.55, -0.30, 0.22]
    target_rpy: [3.14, 0.0, -1.57]
    seed_from_joint_states: true
    sleep_after: 0.7

  - name: place
    target_xyz: [0.55, 0.30, 0.22]
    target_rpy: [3.14, 0.0, -1.57]
    seed_from_joint_states: true
    sleep_after: 0.0
